package com.example.pengingatku.utils

const val EXTRA_ALARM_ID = "alarm_id"
const val ALARM_NOTIFICATION_CHANNEL_ID = "ALARM_CHANNEL_ID"
const val ALARM_NOTIFICATION_CONTENT_TITLE = "Alarm Notification"
const val ALARM_NOTIFICATION_CONTENT_TEXT = "ALARM RINGING!!!"


const val PRE_ALARM_DIFF_IN_MINUTES = 5
const val EXTRA_PRE_ALARM_ID = "pre_alarm_id"
const val PRE_ALARM_NOTIFICATION_CHANNEL_ID = "PRE_ALARM_CHANNEL_ID"
const val PRE_ALARM_NOTIFICATION_CONTENT_TITLE = "Pre-alarm Notification"
const val PRE_ALARM_NOTIFICATION_CONTENT_TEXT= "$PRE_ALARM_DIFF_IN_MINUTES MINUTES BEFORE ALARM RINGING"
